export declare const enum TransformerTypes {
    APPEND = "APPEND",
    CAPITALIZE = "CAPITALIZE",
    FLOAT = "FLOAT",
    INTEGER = "INTEGER",
    PREPEND = "PREPEND",
    REGEX = "REGEX",
    REMOVE_NON_NUMERIC = "REMOVE_NON_NUMERIC",
    REMOVE_NUMERIC = "REMOVE_NUMERIC",
    REPLACE = "REPLACE",
    TO_LOWER_CASE = "TO_LOWER_CASE",
    TO_UPPER_CASE = "TO_UPPER_CASE",
    TRIM = "TRIM"
}
